### ISSUE TITLE
请问支持netkeeper4.0以上么

### ISSUE THREAD

**Issue by zanzhz1101** [CCnut/feed-netkeeper#1]

**Comment by zanzhz1101** [comment]
如果不支持的话，请问能否将拦截拨号法加入插件中，多谢

**Comment by cc5771027** [comment]
核心的代码还是@miao1007的，如果上游更新我会跟进。拦截拨号暂时还不会做进去，有空会考虑支持。

**Comment by CCnut** [comment]
> 如果不支持的话，请问能否将拦截拨号法加入插件中，多谢

已经加入闪讯拦截插件
