### ISSUE TITLE
设置MAC地址后没有产生作用，路由器接口界面依旧显示全“0”MAC地址

### ISSUE THREAD

**Issue by Elletear** [CCnut/feed-netkeeper#10]
设备型号：Newifi3（D2）路由器

固件代码：自编译lean的源码
说明：试了三个分支的编译，发现只有LUA版本才能在WAN接口设置处找到闪讯拨号,另外两个版本直接找不到该方式。

使用LUA版本后发现该分支源码闪讯拨号正常，但MAC设置不能起作用；该版本的闪讯拦截插件设置后不能马上运行，只能重启解决。

![mac](https://user-images.githubusercontent.com/70796317/94365457-c5344980-0103-11eb-86b2-6842d9ab680c.jpg)

**Comment by CCnut** [comment]
请提供下日志

**Comment by CCnut** [comment]
MAC修改功能没啥用，想改mac地址请用macvlan

**Comment by CCnut** [comment]
重启后才能运行问题已经修复

**Comment by CCnut** [comment]
f4c11aa

**Comment by Elletear** [comment]
使用三个分支的代码编译的固件及使用后的系统日志已上传，希望能有作用：https://cowtransfer.com/s/3caad93fdfbf45  提取码：x46dfe
个人查看日志仅看到闪讯拦截的一条与netkeeper相关，但没什么作用：
Thu Sep 24 10:02:38 2020 user.notice root: /tmp/Last_AuthReq Not Found,Try to restore Netkeeper AuthReq
Thu Sep 24 10:02:38 2020 daemon.notice procd: /etc/rc.d/S60netkeeper-interception: cp: can't stat '/etc/netkeeper-interception/AuthReq': No such file or directory
