### ISSUE TITLE
没有闪讯拨号

### ISSUE THREAD

**Issue by v8wzge** [CCnut/feed-netkeeper#14]
为什么我编译出来安装后只有闪讯拦截，没有闪讯拨号啊，用的是lua分支

**Comment by v8wzge** [comment]
是因为snapshot的luci应该用js吗？

**Comment by v8wzge** [comment]
已安装luci-compat，使用的是snapshot分支的OP

**Comment by v8wzge** [comment]
我试了一个遍，都没有闪讯拨号

**Comment by CCnut** [comment]
snapshot的OpenWRT请用master分支

**Comment by v8wzge** [comment]
> snapshot的OpenWRT请用master分支

也没有拨号选项……

**Comment by CCnut** [comment]
把固件发我份，我看下

**Comment by v8wzge** [comment]
https://openwrt.proxy.ustclug.org/snapshots/targets/rockchip/armv8/
官方编译的ext4格式r2s固件

**Comment by v8wzge** [comment]
我是用这个网址内的编译器编译的插件，之后安装到路由器的

**Comment by v8wzge** [comment]
https://openwrt.proxy.ustclug.org/snapshots/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz

**Comment by v8wzge** [comment]
https://openwrt.proxy.ustclug.org/snapshots/targets/rockchip/armv8/openwrt-sdk-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64.tar.xz
我用这个sdk编译的插件包，直接安装到上面的官方编译的固件中

**Comment by v8wzge** [comment]
我编译进固件成功了，但是拨号有问题

**Comment by v8wzge** [comment]
不管是拨号还是拦截都不能用

**Comment by CCnut** [comment]
把你编译的好的包发我

**Comment by v8wzge** [comment]
https://github.com/v8wzge/openwrt-with-docker-for-r2s/releases/download/2020.12.25-1521/openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz
