### ISSUE TITLE
怎么在路由器编译

### ISSUE THREAD

**Issue by coupile** [CCnut/feed-netkeeper#2]
大佬，这个怎么编译

**Comment by hyird** [comment]
太菜了吧

**Comment by evindu** [comment]
@coupile  我教你吧，拦截法不需要编译这么麻烦，直接用miao1007的就可以

**Comment by HumbleHumbert** [comment]
> @coupile 我教你吧，拦截法不需要编译这么麻烦，直接用miao1007的就可以

大神最近有空吗，也教教我吧
