### ISSUE TITLE
添加对lean的op源码的支持吧  还是他的源码用的人多

### ISSUE THREAD

**Issue by hyird** [CCnut/feed-netkeeper#3]
lean的源码 缺少luci-compact 我自己倒腾了下 失败了 
希望能支持下lean的源码

**Comment by CCnut** [comment]
18.06的代码我没测试，luci-compact是19才有的，18我已经移除依赖了，现在18还剩一个已知bug，web gui的启动选项没反应，可以自己用service启动对应服务，过段时间会去修复

**Comment by CCnut** [comment]
已修复
