### ISSUE TITLE
旧的bug去了 新的bug又来了

### ISSUE THREAD

**Issue by hyird** [CCnut/feed-netkeeper#4]
问题1 ：![image](https://user-images.githubusercontent.com/31695447/71618426-756b3500-2bfa-11ea-9c88-46c31a443892.png)   不是时间么  这个是什么鬼  

问题2：![image](https://user-images.githubusercontent.com/31695447/71618436-83b95100-2bfa-11ea-997d-c8b2f6fc564d.png)  拦截的账号 希望能填写进去 我以前账号丢了就靠这个找回来了 

问题3：![image](https://user-images.githubusercontent.com/31695447/71618460-9b90d500-2bfa-11ea-9a37-66df59d600bc.png) 还有不明白这里为什么一直是0 用nk那个脚本  问题2,3 都正常

**Comment by CCnut** [comment]
A1：这个是拦截的账户密码，原始16进制，可以自己转字符串，里面有不可显示字符，所以用16进制输出，其中有两位是账户长度和密码长度。
A2：如上，因为有不可显示字符，所以填进去会出现转换问题。
A3：0数据包一般是没获取到账户密码，获取到账户密码就会正常产生数据，直接用破解插件的工作原理和拦截插件有区别。
