### ISSUE TITLE
分享编译好的ipk for op18 and lede

### ISSUE THREAD

**Issue by hyird** [CCnut/feed-netkeeper#5]
https://livexauatedu-my.sharepoint.com/:u:/g/personal/vergessen_lzx_live_xauat_edu_cn/EQDMxIfZQ0xLoJVEaDwxivgBXwUlyA73awoljxZBC1iB7g?e=7sjOP2

**Comment by lithiumleeow** [comment]
文件已失效 可否再分享一次 谢谢

**Comment by evindu** [comment]
@hyird  文件已失效 可否再分享一次 谢谢

**Comment by Steady66666** [comment]
我编译到路由器上没luci-proto-netkeeper面板，编辑WAN -> 选择闪讯拨号 -> 确认切换，并且没这个，请教一下

**Comment by evindu** [comment]
> 我编译到路由器上没luci-proto-netkeeper面板，编辑WAN -> 选择闪讯拨号 -> 确认切换，并且没这个，请教一下

需要把三个包都编译和安装，如果你是4.0用拦截法的话其实可以不用编译直接用原来的方法。
