### ISSUE TITLE
18.06和19.7编译到固件里都有问题

### ISSUE THREAD

**Issue by YZcrazy** [CCnut/feed-netkeeper#6]
18.06的路由器运行在拨号的时候，路由器cpu会满载，导致路由器卡死。19.7的编译到固件里，network里没有闪讯协议。
 
![EDTG1L}_G_1@X0_X2 4EV8B](https://user-images.githubusercontent.com/46078892/87443225-c6d39280-c627-11ea-9e20-5165d41a4011.png)
![TUJ A$KT%KG87F$TE$336I6](https://user-images.githubusercontent.com/46078892/87443249-cfc46400-c627-11ea-9da1-e9f0f2029897.png)

**Comment by r1172464137** [comment]
> 18.06[，]，[cpu]，]，]，19.7[，网络]
> 
> ![EDTG1L}_G_1@X0_X2 4EV8B](https://user-images.githubusercontent.com/46078892/87443225-c6d39280-c627-11ea-9e20-5165d41a4011.png)
> ![TUJ A$KT%KG87F$TE$336I6](https://user-images.githubusercontent.com/46078892/87443249-cfc46400-c627-11ea-9da1-e9f0f2029897.png)

lienol的源码是跟进openwrt上游的，界面用的是js，18.06用的是lua。至于19.7理论应该能编译进去，但不知道你为什么编译不进去。
可以给你提供一个解决方案，你可以使用lean的源码然后用作者基于18.06的分支进行修改，把pppd的2.4.7改成2.4.8（op上游早已跟进了2.4.8，这个用的是2.4.7，编译出来会有冲突。）

**Comment by CCnut** [comment]
现在主要维护js的版本，lua的版本基本不会去动了

**Comment by CCnut** [comment]
卡死问题已解决
