### ISSUE TITLE
请教一下软件装入OpenWrt的步骤

### ISSUE THREAD

**Issue by YakumoriYukari** [CCnut/feed-netkeeper#9]
最近多人使用多个网络的时候遇到了一个标有content filter的页面，检测说我共享多端登录，禁止我使用校园网五到十分钟，就来尝试一下新的方法，下载文件后依我的水平还是安装不到软件，将几个文件用winscp上传后用opkg和sh的指令瞎试了，没有用，想请作者细写下安装软件的步骤，十分感谢
这个检测我共享多端登录是真的头疼，有几个也弄了这个的寝室也反应有这问题，网用起来时断时续，就是这几天开始的

**Comment by ChristianSwift** [comment]
这个是编译镜像的时候加进去的软件源，不是给你直接装的啊

**Comment by pantongnian** [comment]
能出个怎么编译的教程吗，大佬

**Comment by ChristianSwift** [comment]
> 能出个怎么编译的教程吗，大佬

去问教你操作系统的老师
![image](https://user-images.githubusercontent.com/20925565/100083181-0e92e200-2e84-11eb-8bb9-a90f39236d45.png)
